name: Pull and Test Container

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  get_tags:
    name: Get all container tags
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
    steps:
      - name: Get container package name
        id: get-package-name
        run: echo "package_name=$(echo '${{ github.repository }}' | awk -F'/' '{print $2}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Get container tags
        id: get-tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tags=$(gh api "/users/${{ github.repository_owner }}/packages/container/${{ steps.get-package-name.outputs.package_name }}/versions" -q '.[].metadata.container.tags | select(. != null) | flatten | unique | tojson')
          if [ -z "$tags" ]; then
            tags="[]"
          fi
          delimiter=$(openssl rand -hex 8)
          echo "tags<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "${tags}" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

  smoke_test:
    needs: get_tags
    if: needs.get_tags.outputs.tags != '[]'
    name: Smoke Test Container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        tag: ${{ fromJson(needs.get_tags.outputs.tags) }}
    steps:
      - name: Lowercase repository name
        id: lowercase-repo
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ghcr.io/${{ steps.lowercase-repo.outputs.name }}:${{ matrix.tag }}

      - name: Run in-container test
        run: docker run --rm ghcr.io/${{ steps.lowercase-repo.outputs.name }}:${{ matrix.tag }} pytest /app/tests/test_dry_run.py
